### ISSUE TITLE
Default Selected options in Right Side

### ISSUE THREAD

**Issue by sakthimanikandan845** [novadaemon/filament-combobox#4]
Can we set some options as already selected in this field by default on the right side?

**Comment by novadaemon** [comment]
Shure. It's a great idea.

**Comment by novadaemon** [comment]
Since Combobox extends the **Filament\Forms\Components\Select** class, you can use any of the methods available in that class, including the *default* method: https://filamentphp.com/docs/3.x/forms/fields/getting-started#setting-a-default-value

**Comment by novadaemon** [comment]
Since Combobox extends the Filament\Forms\Components\Select class, you can use any of the methods available in that class, including the default method: https://filamentphp.com/docs/3.x/forms/fields/getting-started#setting-a-default-value
